SGD8-709: Added '@digipolis-gent/opening-hours-widget' npm package
StadGent/drupal_module_opening-hours pull request #29
Opened 2018-12-03 15:39 UTC by hstandaert

2018-12-04 08:06 UTC, delrueba approved these changes

2018-12-06 13:24 UTC, zero2one requested changes

2018-12-06 13:24 UTC, zero2one commented on opening_hours.libraries.yml
> +    - drupal/opening-hours-widget
You also need to define the javascript library:

```yml
library:
  version: 0.0.2
  js:
    /libraries/opening-hours-widget/dist/opening-hours-widget.min.js: { preprocess: false, minified: true }

widget:
  version: 1.x
  js:
    js/opening-hours.functions.js: {}
    js/opening-hours.binding.js: {}
  dependencies:
    - core/jquery
    - core/drupalSettings
    - opening_hours/library
```

2018-12-06 13:32 UTC, hstandaert commented
Todo for self: 
- [ ] Add requirements hook to install file (example at https://cgit.drupalcode.org/lightgallery/tree/lightgallery.install)

2018-12-10 10:23 UTC, zero2one approved these changes

2018-12-10 10:28 UTC, merged