Accessibility improvements
StadGent/drupal_module_opening-hours pull request #32
Opened 2018-12-19 13:40 UTC by hstandaert

- Replaced classes with `aria` attributes
- Updated javascript bindings

2018-12-19 14:19 UTC, delrueba approved these changes

2018-12-20 07:24 UTC, zero2one requested changes

2018-12-20 07:24 UTC, zero2one commented on templates/opening-hours-widget.html.twig
> +{% set widgetId = 'openinghours' ~ service_id ~ (channel_id ? '-' ~ channel_id)  %}
Since a widget can be used several times on the same page for the same service-channel, this sill lead to non unique ID's on the page.
* create a [unique ID](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Html.php/function/Html%3A%3AgetUniqueId/8.2.x) in the preprocessor.

On Visit Gent we show 3 widgets for the same opening hours serviceId-channelId combination on 1 page.

Example: https://visit.gent.be/nl/zien-doen/gravensteen-een-burcht-gent

2018-12-20 09:11 UTC, hstandaert commented on templates/opening-hours-widget.html.twig
> +{% set widgetId = 'openinghours' ~ service_id ~ (channel_id ? '-' ~ channel_id)  %}
Done 👍

2018-12-20 10:35 UTC, zero2one approved these changes

2018-12-20 10:35 UTC, zero2one commented on opening_hours.module
> +        'widget_id' => NULL,
Deze mag hier weg?

2018-12-20 10:36 UTC, zero2one requested changes

2018-12-20 10:36 UTC, zero2one commented on opening_hours.module
> +        'widget_id' => NULL,
Moet weg?

2018-12-20 10:47 UTC, zero2one approved these changes

2018-12-20 10:48 UTC, merged